"""add variant context fields

Revision ID: 05ab37f4bae5
Revises: o1d2e3f4a5b6
Create Date: 2026-06-15 17:15:48.784950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ab37f4bae5'
down_revision = 'o1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deployment_environment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('objectives_profile', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('objectives_profile')
        batch_op.drop_column('platform')
        batch_op.drop_column('deployment_environment')

    # ### end Alembic commands ###
